{% set PKG_NAME = 'c-array-defs' %}
{% set LIB_NAME = 'CArrayDefs' %}

{% if GIT_DESCRIBE_NUMBER > '0' %}
{% set GIT_VERSION = GIT_DESCRIBE_TAG[1:] + '.post' + GIT_DESCRIBE_NUMBER %}
{% else %}
{% set GIT_VERSION = GIT_DESCRIBE_TAG[1:] %}
{% endif %}
# source will be downloaded prior to filling in jinja templates
# Example assumes that this folder has setup.py in it
source:
  git_url: ../

requirements:
  build:
    - platformio-helpers >=0.6

build:
  noarch: generic
  script:
    # Copy Arduino library to Conda include directory
    - python -c
        "import os.path; import os; import shutil; import platformio_helpers as pioh;
        lib_src_dir = os.path.join(os.environ['SRC_DIR'], '{{ LIB_NAME }}');
        install_dir = pioh.conda_arduino_include_path().joinpath('{{ LIB_NAME }}');
        shutil.copytree(lib_src_dir, install_dir);
        "

package:
  name: {{ PKG_NAME }}
  version: {{ GIT_VERSION }}

about:
  home: https://github.com/sci-bots/{{ PKG_NAME }}
  license: MIT
