# source will be downloaded prior to filling in jinja templates
# Example assumes that this folder has setup.py in it
source:
  git_url: ../

build:
  noarch: generic
  script:
    - mkdir "%PREFIX%\Library\include\Arduino"  # [win]
    - xcopy /S /Y /I /Q "%SRC_DIR%"\CArrayDefs "%PREFIX%"\Library\include  # [win]
    - xcopy /S /Y /I /Q "%SRC_DIR%"\CArrayDefs "%PREFIX%"\Library\include\Arduino\CArrayDefs  # [win]
    - mkdir -p "${PREFIX}/include/Arduino"  # [not win]
    - cp -r "${SRC_DIR}/CArrayDefs" "${PREFIX}/include"  # [not win]
    - cp -r "${SRC_DIR}/CArrayDefs" "${PREFIX}/include/Arduino"  # [not win]

package:
  name: c-array-defs
{% if GIT_DESCRIBE_NUMBER > '0' %}
  version: {{ GIT_DESCRIBE_TAG[1:] }}.post{{ GIT_DESCRIBE_NUMBER }}
{% else %}
  version: {{ GIT_DESCRIBE_TAG[1:] }}
{% endif %}

about:
  home: https://github.com/sci-bots/c-array-defs
  license: MIT
